/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
export const domain={
 code:'SQLAGENT',systemName:'知华数据查询智能体',englishName:'ENTERPRISE SQL AGENT',theme:{primary:'#245b82',dark:'#172d3e',accent:'#c4873b'},
 workspace:'集团数据平台 / 查询治理组',fieldWorkspace:'经营分析域 / 数据服务台',period:'2026-08-17 · 实时治理',liveText:'元数据于 14:26 更新',fieldContextLabel:'当前数据域',fieldContext:'经营分析 · 只读环境',fieldUser:'林峤',fieldRole:'数据分析师',adminUser:'许澄',adminRole:'数据平台主管',
 adminTitle:'企业数据查询控制台',adminBreadcrumb:'数据智能 / SQL Agent',adminSubtitle:'把自然语言问题转成带权限、行数限制与审批证据的安全查询计划。',exportAction:'导出审计报告',createAction:'发起查询任务',chartTitle:'查询成功率趋势',chartSubtitle:'一次成功率 / 质量目标',chartLabels:['08:00','09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00'],loadTitle:'数据源查询负载',loadSubtitle:'按连接池与扫描行数计算',recordsTitle:'最近查询任务',recordsSubtitle:'按风险、扫描成本和业务优先级排序',issueTitle:'查询治理提醒',issueSubtitle:'敏感字段、跨域访问与高成本扫描',
 recordName:'查询任务',itemName:'业务问题',unitName:'数据域',batchName:'涉及表',planName:'检查项',doneName:'已通过',exceptionName:'拦截',unitLabel:'项',listBreadcrumb:'SQL Agent / 查询队列',listSubtitle:'每次生成均保留问题、表范围、风险解释、SQL 预览和人工决策。',listSummary:[['今日查询','286'],['自动通过','218'],['待复核','17',true],['已拦截','9']],tabs:['全部','待解析','待复核','执行中','已归档'],
 fieldBreadcrumb:'数据服务台 / 分析师',fieldTitle:'安全查询工作台',fieldSubtitle:'我的任务 8 个 · 待复核 3 个 · 已拦截 1 个',fieldSecondary:'查看执行计划',reportAction:'提交查询反馈',fieldNoticeTitle:'生产连接保持只读',fieldNotice:'敏感字段策略覆盖 98.6%',steps:['意图解析','元数据匹配','SQL 生成','安全校验','人工确认'],documentAction:'查看数据字典',printAction:'导出查询证据',resourceCardTitle:'可用数据资源',resourceValueLabel:'已授权数据表',resourceHealthLabel:'元数据健康度',quickSubtitle:'常用查询入口',
 quickActions:[['生成查询','/shopfloor/report','问题、表范围与结果限制'],['数据字典','/shopfloor/material','指标、字段与业务口径'],['连接状态','/shopfloor/resources','数据源、权限和健康度'],['风险升级','/shopfloor/andon','写意图与敏感访问复核']],reportDefaults:[1,0],reportTitle:'查询结果反馈',reportSubtitle:'记录结果是否匹配问题，以及需要修正的口径。',reportSuccess:'查询反馈已提交',reportPlaceholder:'填写结果偏差、业务口径或字段修正建议',reportFootnote:'反馈将进入数据平台主管复核队列',ruleTitle:'SQL 执行门禁',ruleSubtitle:'SQL-GUARD · V1.0',rules:[['只读事务','禁止自动写入'],['租户条件','必须强制注入'],['敏感字段','字段级授权'],['大表扫描','EXPLAIN 后执行',true]],fieldTotals:[['8','我的任务'],['3','待人工复核'],['146','授权数据表'],['98.6%','策略覆盖率']],
 adminMenus:[['/admin','home','查询控制台'],['/admin/work-orders','order','查询任务'],['/admin/samples','box','数据目录'],['/admin/schedule','calendar','执行窗口'],['/admin/methods','process','安全策略'],['/admin/reviews','quality','人工复核'],['/admin/resources','machine','数据连接'],['/admin/report','chart','查询分析']],fieldMenus:[['/shopfloor','home','查询工作台'],['/shopfloor/report','report','结果反馈'],['/shopfloor/tasks','order','我的查询'],['/shopfloor/material','box','数据字典'],['/shopfloor/resources','machine','连接状态'],['/shopfloor/andon','risk','风险升级',3]],moduleTitles:{tasks:['我的查询任务','查看问题、SQL 预览和审批状态'],material:['企业数据字典','统一查看指标、字段和负责团队'],resources:['数据连接中心','管理连接、权限、限流和健康度'],andon:['高风险查询升级','处理写意图、敏感字段和大表扫描'],samples:['数据目录','维护主题域和表级说明'],schedule:['执行窗口','配置离线查询和高峰限流'],methods:['SQL 安全策略','维护只读、租户和脱敏规则'],reviews:['人工复核','记录通过、驳回和修订意见'],report:['查询质量分析','分析成功率、耗时和拦截原因']},
 tagline:'让业务提问，落到可信的数据证据',storyTitle:'从自然语言问题，<br/>到可审计的安全 SQL',storyText:'自动生成查询草案，同时把权限、敏感字段、扫描成本和人工审批放进同一条链路。',pattern:[1,2,5,8,9,13,16,17,22,25,29,32],loginStats:[['286','今日查询'],['98.6%','策略覆盖'],['17','待人工复核']],loginTitle:'企业数据查询控制台',adminDemo:'治理 / 审计 / 连接',fieldDemo:'提问 / 查询 / 反馈'}
export const records=[{no:'SQL-260817-086',name:'查询华东区本月回款趋势',code:'AR-SUMMARY',unit:'财务数据域',group:'经营分析',plan:8,done:7,exception:1,due:'14:30',batch:'ar_summary + customer',status:'待复核',progress:88,priority:'敏感'},{no:'SQL-260817-082',name:'统计渠道订单取消原因',code:'ORDER-FACT',unit:'供应链数据域',group:'订单运营',plan:6,done:6,exception:0,due:'14:10',batch:'order_fact',status:'已完成',progress:100,priority:'正常'},{no:'SQL-260817-079',name:'分析产品毛利异常门店',code:'MARGIN-MART',unit:'零售数据域',group:'经营分析',plan:9,done:5,exception:2,due:'15:00',batch:'margin_mart + store',status:'执行中',progress:56,priority:'关注'},{no:'SQL-260817-071',name:'批量更新客户等级',code:'CUSTOMER-MDM',unit:'客户数据域',group:'客户运营',plan:5,done:2,exception:3,due:'—',batch:'customer_master',status:'已拦截',progress:40,priority:'高风险'},{no:'SQL-260817-065',name:'查看库存周转慢的物料',code:'INV-SNAPSHOT',unit:'供应链数据域',group:'库存运营',plan:7,done:7,exception:0,due:'13:40',batch:'inventory_snapshot',status:'已归档',progress:100,priority:'正常'}]
export const resources=[{code:'DW-PROD',name:'经营分析数据仓库',unit:'数据平台组',status:'运行中',health:99,value:'86',valueUnit:'表',note:'生产环境只读，延迟 42 ms'},{code:'CRM-RO',name:'CRM 只读副本',unit:'客户数据组',status:'运行中',health:97,value:'34',valueUnit:'表',note:'敏感字段策略已生效'},{code:'META-01',name:'企业元数据与指标库',unit:'数据治理组',status:'复核中',health:95,value:'2,680',valueUnit:'字段',note:'12 个字段待补充业务口径'}]
export const reviews=[{no:'RV-260817-032',title:'客户回款趋势查询',type:'敏感字段复核',detail:'手机号已脱敏 · 许澄',result:'待确认'},{no:'RV-260817-027',title:'订单取消原因查询',type:'执行计划',detail:'扫描 8,620 行 · 林峤',result:'通过'},{no:'RV-260817-018',title:'客户等级批量更新',type:'写操作拦截',detail:'社区版禁止 AI 写入',result:'异常'}]
export const adminMetrics=[['今日查询','286 次','较昨日增加 12%','blue'],['一次成功率','91.8%','目标 90%','green'],['待人工复核','17 项','5 项涉及敏感字段','orange'],['安全拦截','9 项','全部未执行','red']]
export const fieldMetrics=[['我的查询','8','3 项等待复核','blue'],['今日已完成','12','平均 2.4 秒','green'],['需要修订','2','业务口径不完整','orange'],['授权数据表','146','均为只读','slate']]
export const chartActual=[72,76,78,81,84,86,88,90,92],chartTarget=[80,80,82,82,85,85,88,90,90]
export const loads=[['经营分析仓',82,'连接池 41 / 50'],['CRM 只读库',68,'连接池 17 / 25'],['供应链数据集市',56,'连接池 14 / 25'],['元数据服务',43,'QPS 86']]
export const issues=[['敏感','回款查询包含客户联系方式','已应用掩码并等待人工复核','待批准'],['成本','毛利查询预计扫描 220 万行','建议改用月度汇总表','待优化'],['写入','检测到客户等级 UPDATE 意图','系统已阻断且未生成执行 SQL','已拦截']].map(x=>({type:x[0],title:x[1],detail:x[2],status:x[3]}))
